---
title: "Lab Week 8"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Need to tell R to send stuff back to github
Doesn't automatically perform version control pushing stuff back to github

#####



###Load the packages

```{r}
library(tidyverse)
library(sf)
library(tmap)
library(leaflet)
library(spatstat)
library(maptools)
```


###Column graph of Texas oil spills (look at oils spills csv data)

```{r}
oil_spills <- read_csv("oil_spills.csv")

#create a new data frame and filter oil_spills
df <- oil_spills %>% 
  filter(`Accident State` == "TX" & `Accident Year` < 2017) %>% 
  group_by(`Accident Year`) %>% 
  summarise(Loss = sum(`Net Loss (Barrels)`) ) #create new variable called Loss

#change column names
colnames(df) <- c("Year", "Loss")

ggplot(df, aes(x = Year, y = Loss)) +
  geom_col()
```



Half as much oil spilled in TX land over these 7 years than was spilled in the Exxon-Valdez oil spill


### Leaflet plot of spill locations in TX in 2016

```{r}
df_loc <- oil_spills %>% 
  filter(`Accident State` == "TX" & `Accident Year` == 2016) %>% 
  select(Latitude, Longitude, `Net Loss (Barrels)`)

colnames(df_loc) <- c("latitude", "longitude", "net_loss")

oil_sf <- st_as_sf(df_loc, coords = c("longitude", "latitude"), crs = 4326)

leaflet(oil_sf) %>% 
  addTiles() %>% 
  addMarkers() # only have net loss variable, so don't have to specify

```






